### PR TITLE
Feature/docker

### PR DESCRIPTION
**Pull request by daxsis**
Development environment is working, production environment will be ready soon but I think we can merge it so that everyone will pull from master working dev environment already.

Base structure is:
```bash
$ tree -L 4
.
├── README.md
├── docker-compose.prod.yml
├── docker-compose.yml
└── services
    ├── nginx
    │   ├── Dockerfile
    │   └── nginx.conf
    └── web
        ├── Dockerfile
        ├── Dockerfile.prod
        ├── entrypoint.prod.sh
        ├── entrypoint.sh
        ├── env
        │   ├── bin
        │   ├── include
        │   ├── lib
        │   ├── lib64 -> lib
        │   ├── pyvenv.cfg
        │   └── share
        ├── manage.py
        ├── project
        │   ├── __init__.py
        │   ├── __pycache__
        │   └── config.py
        └── requirements.txt

11 directories, 14 files
```

### CODE REVIEW

**Review by SamSDK — APPROVED** [review]
Looks good

**Comment by VimFreeman** [comment]
Can you please write some steps to test this PR in the description? TY

**Comment by daxsis** [comment]
@VimFreeman can you please clarify what do you mean to test this PR?
How the setup process works? check [README.md](https://github.com/NanoProd/StackOverflowMock/pull/12/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17), this shows how to set it up.

**Comment by VimFreeman** [comment]
Ah my bad, totally missed that.

**Review by PhilCarPi — DISMISSED** [review]
The environment setup look good to go. Everything look ok on my end.

**Review by NanoProd — DISMISSED** [review]
Looks good to me

**Review by NanoProd — APPROVED** [review]

**Pull request merged**
